name: Publish Release
on:
  workflow_dispatch:

jobs:

  build:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: download-dependencies
        run: |
          go mod download
      - id: build
        run: |
          ./build.sh
          ls -al

  publish:
    runs-on: [self-hosted, Linux, ARM64]
    needs: [build]
    steps:
      - id: debug
        run: ls -al
