name: Publish Release
on:
  push:
    tags:
      - 'v[0-9]+.**'
jobs:

  build:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: download-dependencies
        run: |
          go mod download
      - id: build
        run: |
          ./build.sh
          ls -al

  publish:
    runs-on: [self-hosted, Linux, ARM64]
    needs: [build]
    steps:
      - name: set-release-version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
      - name: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create-release.outputs.id }}
          assets_path: build/spring-boot-scanner-*